# OpenReview Matcher CircleCI 2.0 configuration file 28
version: 2
jobs:
  build:
    working_directory: ~/openreview-matcher-repo
    docker:
    - image: circleci/python:3.7-node
    - image: circleci/redis:6.0.0
    - image: circleci/mongo:4.4.5
      command: [--replSet,rs0]
    - image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
      environment:
        xpack.security.enabled: false
        transport.host: localhost
    - image: rabbitmq:3.8.19
      environment:
        - RABBITMQ_DEFAULT_USER=openreview
        - RABBITMQ_DEFAULT_PASS=openreview
        - RABBITMQ_DEFAULT_VHOST=localhost
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - ./matcher/service/config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
        - ./matcher/service/config/definitions.json:/etc/rabbitmq/definitions.json:ro
    steps:
    - checkout
    - run:
        name: Initialize Replica Set
        command: |
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          sudo touch /etc/apt/sources.list.d/mongodb-org-4.4.list
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org=4.4.5 mongodb-org-server=4.4.5 mongodb-org-shell=4.4.5 mongodb-org-mongos=4.4.5 mongodb-org-tools=4.4.5
          mongo mongodb://localhost:27017 --eval "rs.initiate()"
    - run: git clone https://$OPENREVIEW_GITHUB@github.com/iesl/openreview.git ~/openreview
    - run: git clone https://$OPENREVIEW_GITHUB@github.com/iesl/openreview-py.git ~/openreview-py
    - run: mkdir ~/openreview/logs
    - run:
        name: install openreview
        command: |
          cd ~/openreview
          npm install
          mkdir files
    - run:
        name: run app
        command: |
          cd ~/openreview
          NODE_ENV=circleci node scripts/clean_start_app.js
        background: true
    - run:
        name: install dependencies
        command: |
          cd ~/openreview-matcher-repo
          pip install -e .
    - run:
        name: install the local openreview-py as a dependency
        command: |
          cd ~/openreview-matcher-repo
          pip install -e ~/openreview-py
    - run:
        name: run celery worker
        command: |
          cd ~/openreview-matcher-repo
          celery --app matcher.service.server.celery_app worker --loglevel=INFO -n worker -c 1
        background: true
    - run:
        name: run tests
        command: |
          cd ~/openreview-matcher-repo
          mkdir reports
          mkdir reports/pytest
          python -m pytest -s tests --junitxml=reports/pytest/pytest-report.xml
    - store_test_results:
        path: reports
    - store_artifacts:
        path: reports
