# OpenReview Matcher CircleCI 2.0 configuration file 13
version: 2
jobs:
  build:
    working_directory: ~/openreview-matcher-repo
    docker:
    - image: circleci/node:8.9.1-stretch
    - image: circleci/python:3.6.1
    - image: circleci/redis:3-stretch
    - image: circleci/mongo:3.6-stretch
    - image: elastic/elasticsearch:6.2.2
    steps:
    - checkout
    - run: git clone https://$OPENREVIEW_GITHUB@github.com/iesl/openreview.git ~/openreview
    - run: mkdir ~/openreview/logs
    - run:
        name: install app
        command: |
          cd ~/openreview
          npm install
          sudo npm install -g grunt-cli
          grunt regen
          mkdir pdfs
          NODE_ENV=circleci node scripts/setup.js
#          NODE_ENV=circleci node scripts/clean_start_app

    - run:
        name: run app
        command: |
          cd ~/openreview
#          NODE_ENV=circleci node app
          NODE_ENV=circleci node scripts/clean_start_app
        background: true
    - run:
        shell: /bin/sh
        command: |
          wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:3000
    - run:
        name: install dependencies
        command: |
          cd ~/openreview-matcher-repo
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    - run:
        name: run tests
        command: |
          cd ~/openreview-matcher-repo
          mkdir test-reports
          python -m pytest tests
    - store_test_results:
        path: test-reports
    - store_artifacts:
        path: test-reports
